### ISSUE TITLE
[Bug]: Example throws an error

### ISSUE THREAD

**Issue by gretzky** [braze-inc/braze-expo-plugin#20]
### Which Platforms?

iOS

### Which React Native Version?

0.78.1

### Which @braze/expo-plugin version?

1.1.1

### Which @braze/react-native-sdk SDK version?

2.1.0

### Repro Rate

100%

### Steps To Reproduce

Clone the repository and follow the steps in the `example/` README.

### Expected Behavior

Expo prebuild should succeed and the example app should run.

### Actual Incorrect Behavior

An error is thrown when running `expo prebuild`

### Verbose Logs

```shell
› npx expo prebuild

✔ Created native projects | /android, /ios already created | gitignore already synced
✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 490ms
✖ Config sync failed
Cannot read properties of undefined (reading 'withJsEnginePodfileProps')
TypeError: Cannot read properties of undefined (reading 'withJsEnginePodfileProps')
    at withIosExpoPlugins (/.config/yarn/global/node_modules/@expo/prebuild-config/src/plugins/withDefaultPlugins.ts:58:5)
    at getPrebuildConfig (/.config/yarn/global/node_modules/@expo/prebuild-config/src/getPrebuildConfig.ts:78:14)
    at getPrebuildConfigAsync (.config/yarn/global/node_modules/@expo/prebuild-config/src/getPrebuildConfig.ts:24:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at configureManagedProjectAsync (/.config/yarn/global/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:48:25)
    at prebuildAsync (/.config/yarn/global/node_modules/expo-cli/src/commands/eject/prebuildAppAsync.ts:88:21)
    at actionAsync (/.config/yarn/global/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:37:3)
```

**Comment by wesleyorbin** [comment]
Hi @gretzky. Can you confirm the RN version that you're running? And which Expo version?
